[package]
name = "drbot-sanitize"
description = "Input sanitization for drbot"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
regex.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
