[package]
name = "drbot-jwt"
description = "JWT token handling for drbot"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
ring.workspace = true
