[package]
name = "drbot-id"
description = "ID generation for drbot"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
uuid.workspace = true
chrono.workspace = true
serde.workspace = true

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(kani)'] }
